require("__LarkenxK2SETweaks__/data/K2SE_matterconversion_vitamelange_data")
require("__LarkenxK2SETweaks__/data/K2SE_matterconversion_naquium_data")
require("__LarkenxK2SETweaks__/data/K2SE_matterconversion_tritium_data")
require("__LarkenxK2SETweaks__/data/K2SE_matterconversion_uranium_data")
require("__LarkenxK2SETweaks__/data/SE_steam_415-975_data")
